version: '3'
services:
  lsphp:
    image: lsphp:lsphp81
    logging:
      driver: none
    volumes:
      - ./sock/lsphp81.sock:/tmp/lsphp81.sock
    restart: always
    networks:
      - default
    ports:
      - 9000:9000

networks:
  default:
    driver: bridge    